version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "tuesday"
      week-of-month: 2
      time: "06:00"
      timezone: "Europe/Berlin"
    assignees:
      - "driiftkiing"
    open-pull-requests-limit: 10
    security-updates-only: true
    commit-message:
      prefix: "security"
